### ISSUE TITLE
It is possible to support R version >= 3.6?

### ISSUE THREAD

**Issue by obromios** [harvard-vpal/heroku-buildpack-r#2]
I want to load the library EpiEstim on heroku, which depends on MCMCpack which depends on R version >=3.6.

EpiEstim appears to be the most popular package for estimating the time varying effective reproduction number, which can provide insights into how well a country is doing with the Covid-19 pandemic. Accordingly, I think quite a few people would appreciate you providing support for the later versions of R.

Also, the repository is using ```packrat```, but that is soft deprecated in favour of ```renv```, so could you consider supporting ```renv```?

**Comment by dpmccabe** [comment]
See these repos, which are still being updated and will have better support for newer R versions and packages:

https://github.com/hmdc/heroku-buildpack-r
https://github.com/hmdc/heroku-docker-r

**Comment by obromios** [comment]
Ok, thank you.
